services:
  backend:
    container_name: post-backend
    build:
      context: ./backend
      target: ${MODE:-prod}
    env_file:
      - .env
    ports:
      - 4000:3001
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net-backend

  frontend:
    container_name: post-frontend
    build: ./frontend
    ports:
      - 8081:80
    networks:
      - net-frontend

  db:
    container_name: postgres
    restart: always
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db-data:${POSTGRES_PGDATA}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net-backend

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - net-backend

volumes:
  db-data: {}

networks:
  net-backend: {}
  net-frontend: {}
